import streamlit as st
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path(__file__).parent.parent))

from utils.kpi_calculator import compute_kpis, top_products, calculate_category_performance
from models.anomaly_detection import detect_anomalies_zscore
from ai.insights_generator import (
    generate_executive_summary,
    answer_custom_question,
    initialize_gemini
)

st.set_page_config(page_title="AI Insights", page_icon="💡", layout="wide")

st.title("💡 AI-Powered Business Insights")
st.markdown("### Gemini AI generates actionable recommendations from your data")

# Check for data
if 'df' not in st.session_state:
    st.warning("⚠️ No data loaded. Please go to the main page and load data first.")
    if st.button("← Go to Main Page"):
        st.switch_page("app.py")
    st.stop()

df = st.session_state['df']
kpis = st.session_state['kpis']

# Check Gemini API
model = initialize_gemini()
if model is None:
    st.error("""
    ❌ **Gemini API Key Not Found**
    
    To use AI insights, please set your Gemini API key:
    
    1. Get a free API key from: https://makersuite.google.com/app/apikey
    2. Set environment variable: `GEMINI_API_KEY=your_key_here`
    3. Restart the application
    
    **Alternative:** Use command line:
    ```bash
    export GEMINI_API_KEY="your_key_here"
    streamlit run app.py
    ```
    """)
    st.stop()



# Inject CSS to make tabs flex evenly
st.markdown("""
<style>
/* Make Streamlit tabs distribute evenly */
div[data-baseweb="tab-list"] {
    display: flex !important;
    justify-content: space-between !important;
    flex-wrap: wrap !important;
}

div[data-baseweb="tab"] {
    flex: 1 1 auto !important;
    text-align: center !important;
    max-width: none !important;
    padding: 0.75rem 1rem !important;
}
</style>
""", unsafe_allow_html=True)

# Tabs for different insight types
tab1, tab2, tab3, tab4 = st.tabs([
    "📊 Executive Summary",
    "💬 Ask Questions",
    "🎯 Performance Analysis",
    "📈 Strategic Recommendations"
])

# Tab 1: Executive Summary
with tab1:
    st.markdown("## 📊 AI-Generated Executive Summary")
    st.markdown("Get a comprehensive overview of your business performance powered by Gemini AI.")
    
    col1, col2 = st.columns([3, 1])
    
    with col1:
        st.info("""
        **What you'll get:**
        - High-level performance summary
        - Key insights and trends
        - Top performing products analysis
        - Anomaly highlights
        - Actionable recommendations
        """)
    
    with col2:
        st.metric("Data Points", f"{len(df):,}")
        st.metric("Date Range", f"{(df['Date'].max() - df['Date'].min()).days} days")
        st.metric("Products", kpis['unique_products'])
    
    if st.button("🤖 Generate Executive Summary", type="primary", use_container_width=True):
        with st.spinner("AI is analyzing your business data... This may take 10-20 seconds."):
            
            # Prepare data
            top_prods = top_products(df, n=5)
            anomalies = detect_anomalies_zscore(st.session_state['daily_df'])
            
            # Generate summary with discount context
            summary = generate_executive_summary(kpis, top_prods, anomalies, df=df)
            
            st.session_state['executive_summary'] = summary
            st.success("✅ Executive summary generated!")
    
    if 'executive_summary' in st.session_state:
        st.markdown("---")
        st.markdown("### 📝 Summary Report")
        st.markdown(st.session_state['executive_summary'])
        
        # Export option
        col1, col2, col3 = st.columns([1, 1, 2])
        
        with col1:
            st.download_button(
                "📥 Download as Text",
                st.session_state['executive_summary'],
                "executive_summary.txt",
                "text/plain",
                use_container_width=True
            )
        
        with col2:
            # Create markdown file
            md_content = f"""# Executive Summary
Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}

{st.session_state['executive_summary']}

---
*Generated by Enterprise Predictive Analytics AI*
"""
            st.download_button(
                "📥 Download as Markdown",
                md_content,
                "executive_summary.md",
                "text/markdown",
                use_container_width=True
            )

# Tab 2: Ask Questions
with tab2:
    st.markdown("## 💬 Ask AI About Your Business")
    st.markdown("Ask any question about your sales data and get AI-powered answers.")
    
    
    
    # Predefined questions (displayed as quick-fill buttons)
    predefined = [
        "Which products should I promote more heavily?",
        "What are the main trends in my sales data?",
        "How can I increase my average transaction value?",
        "What days/times have the highest sales?",
        "What risks should I be monitoring?"
    ]

    st.markdown("### ✨ Quick questions (tap to fill)")
    cols = st.columns(2)
    for i, q_text in enumerate(predefined):
        col = cols[i % len(cols)]
        if col.button(q_text, key=f"pref_q_{i}"):
            st.session_state['custom_question'] = q_text

    # Text area for free typing. Uses session_state so quick-fill buttons work.
    if 'custom_question' not in st.session_state:
        st.session_state['custom_question'] = ""

    question = st.text_area(
        "Your question:",
        value=st.session_state.get('custom_question', ''),
        placeholder="Type any question here, e.g., What products have declining sales and why?",
        height=100,
        key='custom_question'
    )

    # Ensure button works with any non-empty input
    if st.button("🤖 Get AI Answer") and question.strip():
        with st.spinner("AI is analyzing your question..."):
            
            # Prepare data summary
            top_prods = top_products(df, n=10)
            cat_perf = calculate_category_performance(df)
            
            df_summary = f"""
KPIs: {kpis}

Top 10 Products:
{top_prods.to_string()}

Category Performance:
{cat_perf.head(5).to_string()}

Date Range: {df['Date'].min().date()} to {df['Date'].max().date()}
Total Transactions: {len(df):,}
"""
            
            answer = answer_custom_question(question, df_summary)
            
            st.markdown("---")
            st.markdown("### 🤖 AI Answer")
            st.markdown(answer)
            
            # Save to history
            if 'qa_history' not in st.session_state:
                st.session_state['qa_history'] = []
            
            st.session_state['qa_history'].append({
                'timestamp': pd.Timestamp.now(),
                'question': question,
                'answer': answer
            })
    
    # Q&A History
    if 'qa_history' in st.session_state and st.session_state['qa_history']:
        st.markdown("---")
        st.markdown("### 📜 Q&A History")
        
        for i, qa in enumerate(reversed(st.session_state['qa_history'][-5:])):
            with st.expander(f"Q: {qa['question'][:80]}... ({qa['timestamp'].strftime('%H:%M:%S')})"):
                st.markdown(f"**Question:** {qa['question']}")
                st.markdown(f"**Answer:** {qa['answer']}")


# Tab 3: Performance Analysis
with tab3:
    st.markdown("## 🎯 Detailed Performance Analysis")
    
    analysis_type = st.selectbox(
        "Select analysis type:",
        [
            "Product Performance Deep Dive",
            "Category Trend Analysis",
            "Sales Pattern Recognition",
            "Customer Behavior Insights",
            "Competitive Position Analysis"
        ]
    )
    
    if st.button("🔍 Run Analysis", type="primary"):
        with st.spinner(f"Running {analysis_type}..."):
            
            if analysis_type == "Product Performance Deep Dive":
                top_prods = top_products(df, n=10)
                
                prompt_context = f"""
Analyze these top 10 products in detail:
{top_prods.to_string()}

Total sales: ¥{kpis['total_sales']:,.2f}
Average sale: ¥{kpis['avg_sale']:.2f}

Provide:
1. Performance ranking explanation
2. Revenue concentration analysis
3. Product portfolio recommendations
4. Cross-selling opportunities
5. Products to watch (potential issues)
"""
                
                question = "Provide a detailed product performance analysis"
                answer = answer_custom_question(question, prompt_context)
                
            elif analysis_type == "Category Trend Analysis":
                cat_perf = calculate_category_performance(df)
                
                prompt_context = f"""
Category performance data:
{cat_perf.to_string()}

Analyze trends, growth potential, and strategic recommendations for each category.
"""
                
                question = "Analyze category trends and provide strategic recommendations"
                answer = answer_custom_question(question, prompt_context)
                
            elif analysis_type == "Sales Pattern Recognition":
                daily_df = st.session_state['daily_df']
                
                # Add day of week analysis
                daily_df['DayOfWeek'] = daily_df['Date'].dt.day_name()
                dow_sales = daily_df.groupby('DayOfWeek')['daily_sales'].mean().to_dict()
                
                prompt_context = f"""
Daily sales statistics:
- Mean: ¥{daily_df['daily_sales'].mean():,.2f}
- Median: ¥{daily_df['daily_sales'].median():,.2f}
- Std Dev: ¥{daily_df['daily_sales'].std():,.2f}

Day of week averages:
{dow_sales}

Identify patterns, seasonality, and optimization opportunities.
"""
                
                question = "Identify sales patterns and provide optimization recommendations"
                answer = answer_custom_question(question, prompt_context)
                
            elif analysis_type == "Customer Behavior Insights":
                # Analyze transaction patterns
                hourly_pattern = df.groupby(pd.to_datetime(df['Time'], format='mixed').dt.hour)['TotalSales'].mean().to_dict()
                
                prompt_context = f"""
Transaction insights:
- Total transactions: {len(df):,}
- Average transaction: ¥{kpis['avg_sale']:.2f}
- Max transaction: ¥{kpis['max_sale']:.2f}

Hourly sales patterns (avg):
{hourly_pattern}

Analyze customer behavior and recommend strategies to increase engagement and sales.
"""
                
                question = "Analyze customer behavior patterns and provide recommendations"
                answer = answer_custom_question(question, prompt_context)
                
            else:  # Competitive Position Analysis
                top_prods = top_products(df, n=5)
                
                prompt_context = f"""
Business overview:
- Total sales: ¥{kpis['total_sales']:,.2f}
- Growth rate: {((st.session_state['daily_df'].tail(30)['daily_sales'].mean() / st.session_state['daily_df'].head(30)['daily_sales'].mean() - 1) * 100):.2f}%
- Product diversity: {kpis['unique_products']} products

Top products:
{top_prods.to_string()}

Analyze competitive positioning and strategic recommendations.
"""
                
                question = "Analyze competitive position and provide strategic recommendations"
                answer = answer_custom_question(question, prompt_context)
            
            st.markdown("---")
            st.markdown(f"### 📊 {analysis_type}")
            st.markdown(answer)
            
            # Save analysis
            if st.button("💾 Save This Analysis"):
                if 'saved_analyses' not in st.session_state:
                    st.session_state['saved_analyses'] = []
                
                st.session_state['saved_analyses'].append({
                    'timestamp': pd.Timestamp.now(),
                    'type': analysis_type,
                    'content': answer
                })
                
                st.success("✅ Analysis saved!")

# Tab 4: Strategic Recommendations
with tab4:
    st.markdown("## 📈 Strategic Recommendations")
    st.markdown("Get comprehensive strategic guidance based on your data.")
    
    focus_area = st.multiselect(
        "Select focus areas:",
        [
            "Revenue Growth",
            "Cost Reduction",
            "Risk Mitigation",
            "Customer Retention",
            "Market Expansion",
            "Operational Efficiency"
        ],
        default=["Revenue Growth", "Operational Efficiency"]
    )
    
    time_horizon = st.radio(
        "Planning horizon:",
        ["Short-term (1-3 months)", "Medium-term (3-6 months)", "Long-term (6-12 months)"],
        horizontal=True
    )
    
    if st.button("🎯 Generate Strategic Plan", type="primary"):
        with st.spinner("AI is creating your strategic plan..."):
            
            # Prepare comprehensive context
            top_prods = top_products(df, n=10)
            cat_perf = calculate_category_performance(df)
            anomalies = detect_anomalies_zscore(st.session_state['daily_df'])
            
            context = f"""
Business Context:
{kpis}

Focus Areas: {', '.join(focus_area)}
Time Horizon: {time_horizon}

Top Products:
{top_prods.to_string()}

Categories:
{cat_perf.to_string()}

Anomalies: {len(anomalies)} unusual days detected
"""
            
            question = f"""
Create a comprehensive strategic plan focusing on: {', '.join(focus_area)}
Time horizon: {time_horizon}

Provide:
1. Executive summary of current situation
2. Specific recommendations for each focus area
3. Action items with priorities
4. Expected outcomes and KPIs to track
5. Risk factors to monitor
6. Resource requirements

Be specific, actionable, and data-driven.
"""
            
            plan = answer_custom_question(question, context)
            
            st.markdown("---")
            st.markdown("### 📋 Strategic Plan")
            st.markdown(plan)
            
            # Export options
            col1, col2 = st.columns(2)
            
            with col1:
                st.download_button(
                    "📥 Download Strategic Plan",
                    plan,
                    "strategic_plan.txt",
                    "text/plain",
                    use_container_width=True
                )
            
            with col2:
                # Create detailed report
                report = f"""
# Strategic Business Plan
Generated: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M')}

## Focus Areas
{', '.join(focus_area)}

## Planning Horizon
{time_horizon}

## Current Performance Snapshot
- Total Sales: ¥{kpis['total_sales']:,.2f}
- Transactions: {kpis['row_count']:,}
- Products: {kpis['unique_products']}
- Date Range: {kpis['date_range']}

---

{plan}

---
*Generated by Enterprise Predictive Analytics AI*
*This plan should be reviewed and adapted based on your specific business context*
"""
                
                st.download_button(
                    "📄 Download Full Report",
                    report,
                    "strategic_plan_full.md",
                    "text/markdown",
                    use_container_width=True
                )

# Saved analyses section
if 'saved_analyses' in st.session_state and len(st.session_state['saved_analyses']) > 0:
    st.markdown("---")
    st.markdown("## 💾 Saved Analyses")
    
    for i, analysis in enumerate(reversed(st.session_state['saved_analyses'])):
        with st.expander(f"{analysis['type']} - {analysis['timestamp'].strftime('%Y-%m-%d %H:%M')}"):
            st.markdown(analysis['content'])
            
            if st.button(f"🗑️ Delete", key=f"delete_{i}"):
                st.session_state['saved_analyses'].remove(analysis)
                st.rerun()

# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: #666;'>
    <p>💡 AI insights are generated by Gemini AI and should be validated with business judgment</p>
    <p style='font-size: 0.8rem;'>All analyses are based on your historical data and current market context</p>
</div>
""", unsafe_allow_html=True)